export const FRANCE = [
  {
    department: 'Ain',
    department_value: '01',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Aisne',
    department_value: '02',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Allier',
    department_value: '03',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Alpes de Haute-Provence',
    department_value: '04',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Hautes-Alpes',
    department_value: '05',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Alpes-Maritimes',
    department_value: '06',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie de Nice',
    academy_value: 'NICE',
  },
  {
    department: 'Ardèche',
    department_value: '07',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Ardennes',
    department_value: '08',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Ariège',
    department_value: '09',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Aube',
    department_value: '10',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Aude',
    department_value: '11',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Aveyron',
    department_value: '12',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Bouches-du-Rhône',
    department_value: '13',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Calvados',
    department_value: '14',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Cantal',
    department_value: '15',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Charente',
    department_value: '16',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Charente-Maritime',
    department_value: '17',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Cher',
    department_value: '18',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Corrèze',
    department_value: '19',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Corse-du-Sud',
    department_value: '2A',
    region: 'Corse',
    region_value: '20R',
    academy: 'Académie de Corse',
    academy_value: 'CORSE',
  },
  {
    department: 'Haute-Corse',
    department_value: '2B',
    region: 'Corse',
    region_value: '20R',
    academy: 'Académie de Corse',
    academy_value: 'CORSE',
  },
  {
    department: 'Côte-d’Or',
    department_value: '21',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Côtes d’Armor',
    department_value: '22',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Creuse',
    department_value: '23',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Dordogne',
    department_value: '24',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Doubs',
    department_value: '25',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Drôme',
    department_value: '26',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Eure',
    department_value: '27',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Eure-et-Loir',
    department_value: '28',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Finistère',
    department_value: '29',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Gard',
    department_value: '30',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Haute-Garonne',
    department_value: '31',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Gers',
    department_value: '32',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Gironde',
    department_value: '33',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Hérault',
    department_value: '34',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Ille-et-Vilaine',
    department_value: '35',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Indre',
    department_value: '36',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Indre-et-Loire',
    department_value: '37',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Isère',
    department_value: '38',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Jura',
    department_value: '39',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Landes',
    department_value: '40',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Loir-et-Cher',
    department_value: '41',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Loire',
    department_value: '42',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Haute-Loire',
    department_value: '43',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Loire-Atlantique',
    department_value: '44',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Loiret',
    department_value: '45',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Lot',
    department_value: '46',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Lot-et-Garonne',
    department_value: '47',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Lozère',
    department_value: '48',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Maine-et-Loire',
    department_value: '49',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Manche',
    department_value: '50',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Marne',
    department_value: '51',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Haute-Marne',
    department_value: '52',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Mayenne',
    department_value: '53',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Meurthe-et-Moselle',
    department_value: '54',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Meuse',
    department_value: '55',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Morbihan',
    department_value: '56',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Moselle',
    department_value: '57',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Nièvre',
    department_value: '58',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Nord',
    department_value: '59',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie de Lille',
    academy_value: 'LILLE',
  },
  {
    department: 'Oise',
    department_value: '60',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Orne',
    department_value: '61',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Pas-de-Calais',
    department_value: '62',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie de Lille',
    academy_value: 'LILLE',
  },
  {
    department: 'Puy-de-Dôme',
    department_value: '63',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Pyrénées-Atlantiques',
    department_value: '64',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Hautes-Pyrénées',
    department_value: '65',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Pyrénées-Orientales',
    department_value: '66',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Bas-Rhin',
    department_value: '67',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Strasbourg',
    academy_value: 'STRASBOURG',
  },
  {
    department: 'Haut-Rhin',
    department_value: '68',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Strasbourg',
    academy_value: 'STRASBOURG',
  },
  {
    department: 'Rhône',
    department_value: '69',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Haute-Saône',
    department_value: '70',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Saône-et-Loire',
    department_value: '71',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Sarthe',
    department_value: '72',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Savoie',
    department_value: '73',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Haute-Savoie',
    department_value: '74',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Paris',
    department_value: '75',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Paris',
    academy_value: 'PARIS',
  },
  {
    department: 'Seine-Maritime',
    department_value: '76',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Seine-et-Marne',
    department_value: '77',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Yvelines',
    department_value: '78',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Deux-Sèvres',
    department_value: '79',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Somme',
    department_value: '80',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Tarn',
    department_value: '81',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Tarn-et-Garonne',
    department_value: '82',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Var',
    department_value: '83',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie de Nice',
    academy_value: 'NICE',
  },
  {
    department: 'Vaucluse',
    department_value: '84',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Vendée',
    department_value: '85',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Vienne',
    department_value: '86',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Haute-Vienne',
    department_value: '87',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Vosges',
    department_value: '88',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Yonne',
    department_value: '89',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Territoire-de-Belfort',
    department_value: '90',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Essonne',
    department_value: '91',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Hauts-de-Seine',
    department_value: '92',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Seine-Saint-Denis',
    department_value: '93',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Val-de-Marne',
    department_value: '94',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Val-d’Oise',
    department_value: '95',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Guadeloupe',
    department_value: '971',
    region: 'Guadeloupe',
    region_value: '971',
    academy: 'Académie de Guadeloupe',
    academy_value: 'GUADELOUPE',
  },
  {
    department: 'Martinique',
    department_value: '972',
    region: 'Martinique',
    region_value: '972',
    academy: 'Académie de Martinique',
    academy_value: 'MARTINIQUE',
  },
  {
    department: 'Guyane française',
    department_value: '973',
    region: 'Guyane',
    region_value: '973',
    academy: 'Académie de Guyane',
    academy_value: 'GUYANE',
  },
  {
    department: 'La Réunion',
    department_value: '974',
    region: 'La Réunion',
    region_value: '974',
    academy: 'Académie de La Réunion',
    academy_value: 'REUNION',
  },
  {
    department: 'Mayotte',
    department_value: '976',
    region: 'Mayotte',
    region_value: '976',
    academy: 'Académie de Mayotte',
    academy_value: 'MAYOTTE',
  },
];

// https://www.geonames.org/countries/
export const WORLD = [
  {
    country: 'United Arab Emirates',
    country_value: 'AE',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Afghanistan',
    country_value: 'AF',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Albania',
    country_value: 'AL',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Armenia',
    country_value: 'AM',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Angola',
    country_value: 'AO',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Argentina',
    country_value: 'AR',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Austria',
    country_value: 'AT',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Australia',
    country_value: 'AU',
    continent: 'Oceania',
    continent_value: 'OC',
  },
  {
    country: 'Azerbaijan',
    country_value: 'AZ',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Bosnia and Herzegovina',
    country_value: 'BA',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Bangladesh',
    country_value: 'BD',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Belgium',
    country_value: 'BE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Burkina Faso',
    country_value: 'BF',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Bulgaria',
    country_value: 'BG',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Burundi',
    country_value: 'BI',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Benin',
    country_value: 'BJ',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Brunei Darussalam',
    country_value: 'BN',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Bolivia',
    country_value: 'BO',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Brazil',
    country_value: 'BR',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Bahamas',
    country_value: 'BS',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Bhutan',
    country_value: 'BT',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Botswana',
    country_value: 'BW',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Belarus',
    country_value: 'BY',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Belize',
    country_value: 'BZ',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Canada',
    country_value: 'CA',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Democratic Republic of Congo',
    country_value: 'CD',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Central African Republic',
    country_value: 'CF',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Republic of Congo',
    country_value: 'CG',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Switzerland',
    country_value: 'CH',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Côte d’Ivoire',
    country_value: 'CI',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Chile',
    country_value: 'CL',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Cameroon',
    country_value: 'CM',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'China',
    country_value: 'CN',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Colombia',
    country_value: 'CO',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Costa Rica',
    country_value: 'CR',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Cuba',
    country_value: 'CU',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Cyprus',
    country_value: 'CY',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Czech Republic',
    country_value: 'CZ',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Germany',
    country_value: 'DE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Djibouti',
    country_value: 'DJ',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Denmark',
    country_value: 'DK',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Dominican Republic',
    country_value: 'DO',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Algeria',
    country_value: 'DZ',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Ecuador',
    country_value: 'EC',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Estonia',
    country_value: 'EE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Egypt',
    country_value: 'EG',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Western Sahara',
    country_value: 'EH',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Eritrea',
    country_value: 'ER',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Spain',
    country_value: 'ES',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Ethiopia',
    country_value: 'ET',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Finland',
    country_value: 'FI',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Fiji',
    country_value: 'FJ',
    continent: 'Oceania',
    continent_value: 'OC',
  },
  {
    country: 'Falkland Islands',
    country_value: 'FK',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'France',
    country_value: 'FR',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Gabon',
    country_value: 'GA',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'United Kingdom of Great Britain and Northern Ireland',
    country_value: 'GB',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Greenland',
    country_value: 'GD',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Georgia',
    country_value: 'GE',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'French Guiana',
    country_value: 'GF',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Ghana',
    country_value: 'GH',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Gambia',
    country_value: 'GM',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Guinea',
    country_value: 'GN',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Equatorial Guinea',
    country_value: 'GQ',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Greece',
    country_value: 'GR',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Guatemala',
    country_value: 'GT',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Guinea-Bissau',
    country_value: 'GW',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Guyana',
    country_value: 'GY',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Honduras',
    country_value: 'HN',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Croatia',
    country_value: 'HR',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Haiti',
    country_value: 'HT',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Hungary',
    country_value: 'HU',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Indonesia',
    country_value: 'ID',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Ireland',
    country_value: 'IE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Israel',
    country_value: 'IL',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'India',
    country_value: 'IN',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Iraq',
    country_value: 'IQ',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Iran',
    country_value: 'IR',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Iceland',
    country_value: 'IS',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Italy',
    country_value: 'IT',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Jamaica',
    country_value: 'JM',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Jordan',
    country_value: 'JO',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Japan',
    country_value: 'JP',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Kenya',
    country_value: 'KE',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Kyrgyzstan',
    country_value: 'KG',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Cambodia',
    country_value: 'KH',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'North Korea',
    country_value: 'KP',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'South Korea',
    country_value: 'KR',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Kuwait',
    country_value: 'KW',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Kazakhstan',
    country_value: 'KZ',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Lao People’s Democratic Republic',
    country_value: 'LA',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Lebanon',
    country_value: 'LB',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Sri Lanka',
    country_value: 'LK',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Liberia',
    country_value: 'LR',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Lesotho',
    country_value: 'LS',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Lithuania',
    country_value: 'LT',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Luxembourg',
    country_value: 'LU',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Latvia',
    country_value: 'LV',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Libya',
    country_value: 'LY',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Morocco',
    country_value: 'MA',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Moldova',
    country_value: 'MD',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Montenegro',
    country_value: 'ME',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Madagascar',
    country_value: 'MG',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Macedonia',
    country_value: 'MK',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Mali',
    country_value: 'ML',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Myanmar',
    country_value: 'MM',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Mongolia',
    country_value: 'MN',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Mauritania',
    country_value: 'MR',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Malawi',
    country_value: 'MW',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Mexico',
    country_value: 'MX',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Malaysia',
    country_value: 'MY',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Mozambique',
    country_value: 'MZ',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Namibia',
    country_value: 'NA',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'New Caledonia',
    country_value: 'NC',
    continent: 'Oceania',
    continent_value: 'OC',
  },
  {
    country: 'Niger',
    country_value: 'NE',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Nigeria',
    country_value: 'NG',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Nicaragua',
    country_value: 'NI',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Netherlands',
    country_value: 'NL',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Norway',
    country_value: 'NO',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Nepal',
    country_value: 'NP',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'New Zealand',
    country_value: 'NZ',
    continent: 'Oceania',
    continent_value: 'OC',
  },
  {
    country: 'Oman',
    country_value: 'OM',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Panama',
    country_value: 'PA',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Peru',
    country_value: 'PE',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Papua New Guinea',
    country_value: 'PG',
    continent: 'Oceania',
    continent_value: 'OC',
  },
  {
    country: 'Philippines',
    country_value: 'PH',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Pakistan',
    country_value: 'PK',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Poland',
    country_value: 'PL',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Puerto Rico',
    country_value: 'PR',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Palestine',
    country_value: 'PS',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Portugal',
    country_value: 'PT',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Paraguay',
    country_value: 'PY',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Qatar',
    country_value: 'QA',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Romania',
    country_value: 'RO',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Serbia',
    country_value: 'RS',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Russia',
    country_value: 'RU',
    continent: 'Europe',
    // Technically in Asia, but culturally and politically in Europe
    // But moved to its own continent for better display purposes
    // https://en.wikipedia.org/wiki/Geography_of_Russia#Geographical_divisions
    continent_value: 'RU',
  },
  {
    country: 'Rwanda',
    country_value: 'RW',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Saudi Arabia',
    country_value: 'SA',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Solomon Islands',
    country_value: 'SB',
    continent: 'Oceania',
    continent_value: 'OC',
  },
  {
    country: 'Sudan',
    country_value: 'SD',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Sweden',
    country_value: 'SE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Slovenia',
    country_value: 'SI',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Svalbard and Jan Mayen',
    country_value: 'SJ',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Slovakia',
    country_value: 'SK',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Sierra Leone',
    country_value: 'SL',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Senegal',
    country_value: 'SN',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Somalia',
    country_value: 'SO',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Suriname',
    country_value: 'SR',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'South Sudan',
    country_value: 'SS',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'El Salvador',
    country_value: 'SV',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Syria',
    country_value: 'SY',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Eswatini',
    country_value: 'SZ',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Chad',
    country_value: 'TD',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'French Southern Territories',
    country_value: 'TF',
    continent: 'Antarctica',
    continent_value: 'AN',
  },
  {
    country: 'Togo',
    country_value: 'TG',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Thailand',
    country_value: 'TH',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Tajikistan',
    country_value: 'TJ',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Timor-Leste',
    country_value: 'TL',
    continent: 'Oceania',
    continent_value: 'OC',
  },
  {
    country: 'Turkmenistan',
    country_value: 'TM',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Tunisia',
    country_value: 'TN',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Turkey',
    country_value: 'TR',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Trinidad and Tobago',
    country_value: 'TT',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Taiwan',
    country_value: 'TW',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Tanzania',
    country_value: 'TZ',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Ukraine',
    country_value: 'UA',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Uganda',
    country_value: 'UG',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'United States of America',
    country_value: 'US',
    continent: 'North America',
    continent_value: 'NA',
  },
  {
    country: 'Uruguay',
    country_value: 'UY',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Uzbekistan',
    country_value: 'UZ',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Venezuela',
    country_value: 'VE',
    continent: 'South America',
    continent_value: 'SA',
  },
  {
    country: 'Vietnam',
    country_value: 'VN',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'Vanuatu',
    country_value: 'VU',
    continent: 'Oceania',
    continent_value: 'OC',
  },
  {
    country: 'Kosovo',
    country_value: 'XK',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Yemen',
    country_value: 'YE',
    continent: 'Asia',
    continent_value: 'AS',
  },
  {
    country: 'South Africa',
    country_value: 'ZA',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Zambia',
    country_value: 'ZM',
    continent: 'Africa',
    continent_value: 'AF',
  },
  {
    country: 'Zimbabwe',
    country_value: 'ZW',
    continent: 'Africa',
    continent_value: 'AF',
  },
];
