export const FRANCE = [
  {
    department: 'Ain',
    department_value: '01',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Aisne',
    department_value: '02',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Allier',
    department_value: '03',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Alpes de Haute-Provence',
    department_value: '04',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Hautes-Alpes',
    department_value: '05',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Alpes-Maritimes',
    department_value: '06',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie de Nice',
    academy_value: 'NICE',
  },
  {
    department: 'Ardèche',
    department_value: '07',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Ardennes',
    department_value: '08',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Ariège',
    department_value: '09',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Aube',
    department_value: '10',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Aude',
    department_value: '11',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Aveyron',
    department_value: '12',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Bouches-du-Rhône',
    department_value: '13',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Calvados',
    department_value: '14',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Cantal',
    department_value: '15',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Charente',
    department_value: '16',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Charente-Maritime',
    department_value: '17',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Cher',
    department_value: '18',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Corrèze',
    department_value: '19',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Corse-du-Sud',
    department_value: '2A',
    region: 'Corse',
    region_value: '20R',
    academy: 'Académie de Corse',
    academy_value: 'CORSE',
  },
  {
    department: 'Haute-Corse',
    department_value: '2B',
    region: 'Corse',
    region_value: '20R',
    academy: 'Académie de Corse',
    academy_value: 'CORSE',
  },
  {
    department: 'Côte-d’Or',
    department_value: '21',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Côtes d’Armor',
    department_value: '22',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Creuse',
    department_value: '23',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Dordogne',
    department_value: '24',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Doubs',
    department_value: '25',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Drôme',
    department_value: '26',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Eure',
    department_value: '27',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Eure-et-Loir',
    department_value: '28',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Finistère',
    department_value: '29',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Gard',
    department_value: '30',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Haute-Garonne',
    department_value: '31',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Gers',
    department_value: '32',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Gironde',
    department_value: '33',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Hérault',
    department_value: '34',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Ille-et-Vilaine',
    department_value: '35',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Indre',
    department_value: '36',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Indre-et-Loire',
    department_value: '37',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Isère',
    department_value: '38',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Jura',
    department_value: '39',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Landes',
    department_value: '40',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Loir-et-Cher',
    department_value: '41',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Loire',
    department_value: '42',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Haute-Loire',
    department_value: '43',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Loire-Atlantique',
    department_value: '44',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Loiret',
    department_value: '45',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Lot',
    department_value: '46',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Lot-et-Garonne',
    department_value: '47',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Lozère',
    department_value: '48',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Maine-et-Loire',
    department_value: '49',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Manche',
    department_value: '50',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Marne',
    department_value: '51',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Haute-Marne',
    department_value: '52',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Mayenne',
    department_value: '53',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Meurthe-et-Moselle',
    department_value: '54',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Meuse',
    department_value: '55',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Morbihan',
    department_value: '56',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Moselle',
    department_value: '57',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Nièvre',
    department_value: '58',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Nord',
    department_value: '59',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie de Lille',
    academy_value: 'LILLE',
  },
  {
    department: 'Oise',
    department_value: '60',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Orne',
    department_value: '61',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Pas-de-Calais',
    department_value: '62',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie de Lille',
    academy_value: 'LILLE',
  },
  {
    department: 'Puy-de-Dôme',
    department_value: '63',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Pyrénées-Atlantiques',
    department_value: '64',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Hautes-Pyrénées',
    department_value: '65',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Pyrénées-Orientales',
    department_value: '66',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Bas-Rhin',
    department_value: '67',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Strasbourg',
    academy_value: 'STRASBOURG',
  },
  {
    department: 'Haut-Rhin',
    department_value: '68',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Strasbourg',
    academy_value: 'STRASBOURG',
  },
  {
    department: 'Rhône',
    department_value: '69',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Haute-Saône',
    department_value: '70',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Saône-et-Loire',
    department_value: '71',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Sarthe',
    department_value: '72',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Savoie',
    department_value: '73',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Haute-Savoie',
    department_value: '74',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Paris',
    department_value: '75',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Paris',
    academy_value: 'PARIS',
  },
  {
    department: 'Seine-Maritime',
    department_value: '76',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Seine-et-Marne',
    department_value: '77',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Yvelines',
    department_value: '78',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Deux-Sèvres',
    department_value: '79',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Somme',
    department_value: '80',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Tarn',
    department_value: '81',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Tarn-et-Garonne',
    department_value: '82',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Var',
    department_value: '83',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie de Nice',
    academy_value: 'NICE',
  },
  {
    department: 'Vaucluse',
    department_value: '84',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Vendée',
    department_value: '85',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Vienne',
    department_value: '86',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Haute-Vienne',
    department_value: '87',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Vosges',
    department_value: '88',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Yonne',
    department_value: '89',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Territoire-de-Belfort',
    department_value: '90',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Essonne',
    department_value: '91',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Hauts-de-Seine',
    department_value: '92',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Seine-Saint-Denis',
    department_value: '93',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Val-de-Marne',
    department_value: '94',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Val-d’Oise',
    department_value: '95',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Guadeloupe',
    department_value: '971',
    region: 'Guadeloupe',
    region_value: '971',
    academy: 'Académie de Guadeloupe',
    academy_value: 'GUADELOUPE',
  },
  {
    department: 'Martinique',
    department_value: '972',
    region: 'Martinique',
    region_value: '972',
    academy: 'Académie de Martinique',
    academy_value: 'MARTINIQUE',
  },
  {
    department: 'Guyane française',
    department_value: '973',
    region: 'Guyane',
    region_value: '973',
    academy: 'Académie de Guyane',
    academy_value: 'GUYANE',
  },
  {
    department: 'La Réunion',
    department_value: '974',
    region: 'La Réunion',
    region_value: '974',
    academy: 'Académie de La Réunion',
    academy_value: 'REUNION',
  },
  {
    department: 'Mayotte',
    department_value: '976',
    region: 'Mayotte',
    region_value: '976',
    academy: 'Académie de Mayotte',
    academy_value: 'MAYOTTE',
  },
];

// ISO 3166 from iso.org is used for the list, continents are retrieved from geonames.org
// https://www.iso.org/obp/ui/fr/ -> see the csv in countries.csv
// https://www.geonames.org/countries/
export const WORLD = [
  {
    country: 'Émirats arabes unis',
    country_value: 'AE',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Afghanistan',
    country_value: 'AF',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Albanie',
    country_value: 'AL',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Arménie',
    country_value: 'AM',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Angola',
    country_value: 'AO',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Argentine',
    country_value: 'AR',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Autriche',
    country_value: 'AT',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Australie',
    country_value: 'AU',
    continent: 'Océanie',
    continent_value: 'OC',
  },
  {
    country: 'Azerbaïdjan',
    country_value: 'AZ',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Bosnie-Herzégovine',
    country_value: 'BA',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Bangladesh',
    country_value: 'BD',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Belgique',
    country_value: 'BE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Burkina Faso',
    country_value: 'BF',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Bulgarie',
    country_value: 'BG',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Burundi',
    country_value: 'BI',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Bénin',
    country_value: 'BJ',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Brunéi Darussalam',
    country_value: 'BN',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Bolivie',
    country_value: 'BO',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Brésil',
    country_value: 'BR',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Bahamas',
    country_value: 'BS',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Bhoutan',
    country_value: 'BT',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Botswana',
    country_value: 'BW',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Bélarus',
    country_value: 'BY',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Belize',
    country_value: 'BZ',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Canada',
    country_value: 'CA',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Congo',
    country_value: 'CD',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'République centrafricaine',
    country_value: 'CF',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Congo',
    country_value: 'CG',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Suisse',
    country_value: 'CH',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Côte d’Ivoire',
    country_value: 'CI',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Chili',
    country_value: 'CL',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Cameroun',
    country_value: 'CM',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Chine',
    country_value: 'CN',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Colombie',
    country_value: 'CO',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Costa Rica',
    country_value: 'CR',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Cuba',
    country_value: 'CU',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Chypre',
    country_value: 'CY',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Tchéquie',
    country_value: 'CZ',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Allemagne',
    country_value: 'DE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Djibouti',
    country_value: 'DJ',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Danemark',
    country_value: 'DK',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'République dominicaine',
    country_value: 'DO',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Algérie',
    country_value: 'DZ',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Équateur',
    country_value: 'EC',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Estonie',
    country_value: 'EE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Égypte',
    country_value: 'EG',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Sahara occidental',
    country_value: 'EH',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Érythrée',
    country_value: 'ER',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Espagne',
    country_value: 'ES',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Éthiopie',
    country_value: 'ET',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Finlande',
    country_value: 'FI',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Fidji',
    country_value: 'FJ',
    continent: 'Océanie',
    continent_value: 'OC',
  },
  {
    country: 'Falkland',
    country_value: 'FK',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'France',
    country_value: 'FR',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Gabon',
    country_value: 'GA',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Royaume-Uni de Grande-Bretagne et d’Irlande du Nord',
    country_value: 'GB',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Grenade',
    country_value: 'GD',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Géorgie',
    country_value: 'GE',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Guyane française',
    country_value: 'GF',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Ghana',
    country_value: 'GH',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Gambie',
    country_value: 'GM',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Guinée',
    country_value: 'GN',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Guinée équatoriale',
    country_value: 'GQ',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Grèce',
    country_value: 'GR',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Guatemala',
    country_value: 'GT',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Guinée-Bissau',
    country_value: 'GW',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Guyana',
    country_value: 'GY',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Honduras',
    country_value: 'HN',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Croatie',
    country_value: 'HR',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Haïti',
    country_value: 'HT',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Hongrie',
    country_value: 'HU',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Indonésie',
    country_value: 'ID',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Irlande',
    country_value: 'IE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Israël',
    country_value: 'IL',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Inde',
    country_value: 'IN',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Iraq',
    country_value: 'IQ',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Iran',
    country_value: 'IR',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Islande',
    country_value: 'IS',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Italie',
    country_value: 'IT',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Jamaïque',
    country_value: 'JM',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Jordanie',
    country_value: 'JO',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Japon',
    country_value: 'JP',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Kenya',
    country_value: 'KE',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Kirghizistan',
    country_value: 'KG',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Cambodge',
    country_value: 'KH',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Corée',
    country_value: 'KP',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Corée',
    country_value: 'KR',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Koweït',
    country_value: 'KW',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Kazakhstan',
    country_value: 'KZ',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Lao',
    country_value: 'LA',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Liban',
    country_value: 'LB',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Sri Lanka',
    country_value: 'LK',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Libéria',
    country_value: 'LR',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Lesotho',
    country_value: 'LS',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Lituanie',
    country_value: 'LT',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Luxembourg',
    country_value: 'LU',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Lettonie',
    country_value: 'LV',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Libye',
    country_value: 'LY',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Maroc',
    country_value: 'MA',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Moldavie',
    country_value: 'MD',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Monténégro',
    country_value: 'ME',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Madagascar',
    country_value: 'MG',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Macédoine du Nord',
    country_value: 'MK',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Mali',
    country_value: 'ML',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Myanmar',
    country_value: 'MM',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Mongolie',
    country_value: 'MN',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Mauritanie',
    country_value: 'MR',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Malawi',
    country_value: 'MW',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Mexique',
    country_value: 'MX',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Malaisie',
    country_value: 'MY',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Mozambique',
    country_value: 'MZ',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Namibie',
    country_value: 'NA',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Nouvelle-Calédonie',
    country_value: 'NC',
    continent: 'Océanie',
    continent_value: 'OC',
  },
  {
    country: 'Niger',
    country_value: 'NE',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Nigéria',
    country_value: 'NG',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Nicaragua',
    country_value: 'NI',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Pays-Bas',
    country_value: 'NL',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Norvège',
    country_value: 'NO',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Népal',
    country_value: 'NP',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Nouvelle-Zélande',
    country_value: 'NZ',
    continent: 'Océanie',
    continent_value: 'OC',
  },
  {
    country: 'Oman',
    country_value: 'OM',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Panama',
    country_value: 'PA',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Pérou',
    country_value: 'PE',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Papouasie-Nouvelle-Guinée',
    country_value: 'PG',
    continent: 'Océanie',
    continent_value: 'OC',
  },
  {
    country: 'Philippines',
    country_value: 'PH',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Pakistan',
    country_value: 'PK',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Pologne',
    country_value: 'PL',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Porto Rico',
    country_value: 'PR',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Portugal',
    country_value: 'PT',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Paraguay',
    country_value: 'PY',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Qatar',
    country_value: 'QA',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Roumanie',
    country_value: 'RO',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Serbie',
    country_value: 'RS',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Russie',
    country_value: 'RU',
    continent: 'Europe',
    // Technically in Asia, but culturally and politically in Europe
    // But moved to its own continent for better display purposes
    // https://en.wikipedia.org/wiki/Geography_of_Russia#Geographical_divisions
    continent_value: 'RU',
  },
  {
    country: 'Rwanda',
    country_value: 'RW',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Arabie saoudite',
    country_value: 'SA',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Salomon',
    country_value: 'SB',
    continent: 'Océanie',
    continent_value: 'OC',
  },
  {
    country: 'Soudan',
    country_value: 'SD',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Suède',
    country_value: 'SE',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Slovénie',
    country_value: 'SI',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Svalbard et l’Île Jan Mayen',
    country_value: 'SJ',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Slovaquie',
    country_value: 'SK',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Sierra Leone',
    country_value: 'SL',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Sénégal',
    country_value: 'SN',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Somalie',
    country_value: 'SO',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Suriname',
    country_value: 'SR',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Soudan du Sud',
    country_value: 'SS',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'El Salvador',
    country_value: 'SV',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'République arabe syrienne',
    country_value: 'SY',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Eswatini',
    country_value: 'SZ',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Tchad',
    country_value: 'TD',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Terres australes françaises',
    country_value: 'TF',
    continent: 'Antarctique',
    continent_value: 'AN',
  },
  {
    country: 'Togo',
    country_value: 'TG',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Thaïlande',
    country_value: 'TH',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Tadjikistan',
    country_value: 'TJ',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Timor-Leste',
    country_value: 'TL',
    continent: 'Océanie',
    continent_value: 'OC',
  },
  {
    country: 'Turkménistan',
    country_value: 'TM',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Tunisie',
    country_value: 'TN',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Türkiye',
    country_value: 'TR',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Trinité-et-Tobago',
    country_value: 'TT',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Taïwan',
    country_value: 'TW',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Ukraine',
    country_value: 'UA',
    continent: 'Europe',
    continent_value: 'EU',
  },
  {
    country: 'Ouganda',
    country_value: 'UG',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'États-Unis d’Amérique',
    country_value: 'US',
    continent: 'Amérique du Nord',
    continent_value: 'NA',
  },
  {
    country: 'Uruguay',
    country_value: 'UY',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Ouzbékistan',
    country_value: 'UZ',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Venezuela',
    country_value: 'VE',
    continent: 'Amérique du Sud',
    continent_value: 'SA',
  },
  {
    country: 'Viet Nam',
    country_value: 'VN',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Vanuatu',
    country_value: 'VU',
    continent: 'Océanie',
    continent_value: 'OC',
  },
  {
    country: 'Yémen',
    country_value: 'YE',
    continent: 'Asie',
    continent_value: 'AS',
  },
  {
    country: 'Afrique du Sud',
    country_value: 'ZA',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Zambie',
    country_value: 'ZM',
    continent: 'Afrique',
    continent_value: 'AF',
  },
  {
    country: 'Zimbabwe',
    country_value: 'ZW',
    continent: 'Afrique',
    continent_value: 'AF',
  },
];
