name: Build HTML docs

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npm run build:docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          user_name: 'GitHub Action'
          user_email: 'action@github.com'
          full_commit_message: 'Update documentation'
